version: '3'
services:
  movies:
    image: rohitpekale07/projectmovies1:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: rohitpekale07/projecttrain1:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: rohitpekale07/projectdth1:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: rohitpekale07/projectrecharge1:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
