version: '3'
services:
  movies:
    image: rohitpekale007/projectmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: rohitpekale007/projecttrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: rohitpekale007/projectdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: rohitpekale007/projectrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
